# ───────────────────────── submissions (ns: submission) ────────────────────────
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: user-manager-ingress
  namespace: user-manager
  annotations:
    nginx.ingress.kubernetes.io/proxy-body-size: "20m"
spec:
  ingressClassName: nginx
  rules:
    - http:
        paths:
         - path: /api/v1/user
           pathType: Prefix
           backend:
             service:
               name: user-manager-service
               port:
                 number: 5050
---
# ───────────────────────── assignments (ns: assignment) ─────────────────────────
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: assignments-ingress
  namespace: assignment
  annotations:
    nginx.ingress.kubernetes.io/proxy-body-size: "20m"
spec:
  ingressClassName: nginx
  rules:
    - http:
        paths:
          - path: /api/v1/assignments
            pathType: Prefix
            backend:
              service:
                name: assignments-service
                port:
                  number: 5050
---
# ───────────────────────── submissions (ns: submission) ────────────────────────
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: submissions-ingress
  namespace: submission
  annotations:
    nginx.ingress.kubernetes.io/proxy-body-size: "100m"    # upload grandi
    nginx.ingress.kubernetes.io/proxy-read-timeout: "600"  # download lunghi
    nginx.ingress.kubernetes.io/proxy-send-timeout: "600"
    nginx.ingress.kubernetes.io/use-regex: "true"          # serve per la rotta "speciale"
spec:
  ingressClassName: nginx
  rules:
    - http:
        paths:
          # Rotta SPECIFICA: /api/v1/assignments/<id>/submissions  -> submissions-service
          - path: /api/v1/assignments/as-\d{5}/submissions(/|$)
            pathType: ImplementationSpecific
            backend:
              service:
                name: submission-service
                port:
                  number: 6060
          # Rotte standard di submissions
          - path: /api/v1/submissions
            pathType: Prefix
            backend:
              service:
                name: submission-service
                port:
                  number: 6060
          - path: /api/v1/files
            pathType: Prefix
            backend:
              service:
                name: submission-service
                port:
                  number: 6060
---
# ───────────────────────── assignments (ns: assignment) ─────────────────────────
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: review-ingress
  namespace: review
  annotations:
    nginx.ingress.kubernetes.io/proxy-body-size: "20m"
spec:
  ingressClassName: nginx
  rules:
    - http:
        paths:
          - path: /api/v1/reviews
            pathType: Prefix
            backend:
              service:
                name: review-service
                port:
                  number: 7070
---
# ───────────────────────── RabbitMQ (ns: rabbitmq) ─────────────────────────────
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: rabbitmq-ui
  namespace: rabbitmq
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  ingressClassName: nginx
  rules:
    - http:
        paths:
          - path: /rabbitmq
            pathType: Prefix
            backend:
              service:
                name: rabbitmq
                port:
                  number: 15672
---
# ───────────────────────── Report (ns: report) ─────────────────────────
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: report-ingress
  namespace: report
  annotations:
    nginx.ingress.kubernetes.io/proxy-body-size: "20m"
spec:
  ingressClassName: nginx
  rules:
    - http:
        paths:
          - path: /api/v1/report
            pathType: Prefix
            backend:
              service:
                name: report-service
                port:
                  number: 9090