replicaCount: 1

auth:
  username: admin
  password: pass12345
  erlangCookie: ryG8Vf2dUZhYmG4MkqUK16tpJGc/PHBSaKDVyJJ/CB0=

persistence:
  enabled: true
  size: 2Gi

resources:
  requests:
    cpu: "250m"
    memory: "512Mi"
  limits:
    cpu: "1"
    memory: "1Gi"

service:
  type: ClusterIP 

plugins: "rabbitmq_management rabbitmq_prometheus"

ingress:
  enabled: false
  ingressClassName: nginx
  hostname: ""             
  path: /rabbitmq
  pathType: Prefix
  tls: false
  annotations:
    nginx.ingress.kubernetes.io/proxy-body-size: "20m"

metrics:
  enabled: false  
