apiVersion: v1
kind: Secret
metadata:
  name: assignment-secrets
  namespace: assignment
type: Opaque
stringData:
  jwt_public.pem: |
    -----BEGIN PUBLIC KEY-----
    MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAveoIk8PEPG+9aalcyIm6
    MPQxCH+plz1RaavmTfu5x3fXL74wZKm0C2lbxPSqhG7kcRhHVnSXKhNJnRDLrpIX
    zO5Amr9d7HbVJOgqxLJoSje9imLEYbdN/4/gWlayIJE1ofJ5UDbo/ongy6hFVLhh
    AGKlXLEhrJCRWhlVDm28MssBoVXg4pCzwr5IfEMDU8hdDo377Q/wj8mC4rDs5rK+
    /cwvMlrE34sHuHdrkNEVE0nb2DcHfanLmBl9a0F+KuTxAyrFDTP4CcZ3pwKzi/tL
    pmelxt0nDj9GUcpp8C1YjBe044ZMNeKghw5ZQtyfpjGr/q8CDGI5HrGTDgGy+sVH
    vQIDAQAB
    -----END PUBLIC KEY-----

---

apiVersion: v1
kind: Secret
metadata:
  name: submission-secrets
  namespace: submission
type: Opaque
stringData:
  jwt_public.pem: |
    -----BEGIN PUBLIC KEY-----
    MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAveoIk8PEPG+9aalcyIm6
    MPQxCH+plz1RaavmTfu5x3fXL74wZKm0C2lbxPSqhG7kcRhHVnSXKhNJnRDLrpIX
    zO5Amr9d7HbVJOgqxLJoSje9imLEYbdN/4/gWlayIJE1ofJ5UDbo/ongy6hFVLhh
    AGKlXLEhrJCRWhlVDm28MssBoVXg4pCzwr5IfEMDU8hdDo377Q/wj8mC4rDs5rK+
    /cwvMlrE34sHuHdrkNEVE0nb2DcHfanLmBl9a0F+KuTxAyrFDTP4CcZ3pwKzi/tL
    pmelxt0nDj9GUcpp8C1YjBe044ZMNeKghw5ZQtyfpjGr/q8CDGI5HrGTDgGy+sVH
    vQIDAQAB
    -----END PUBLIC KEY-----

---

apiVersion: v1
kind: Secret
metadata:
  name: jwt-keys
  namespace: user-manager
type: Opaque
stringData:
  jwt_private.pem: |
    -----BEGIN PRIVATE KEY-----
    MIIEvAIBADANBgkqhkiG9w0BAQEFAASCBKYwggSiAgEAAoIBAQC96giTw8Q8b71p
    qVzIibow9DEIf6mXPVFpq+ZN+7nHd9cvvjBkqbQLaVvE9KqEbuRxGEdWdJcqE0md
    EMuukhfM7kCav13sdtUk6CrEsmhKN72KYsRht03/j+BaVrIgkTWh8nlQNuj+ieDL
    qEVUuGEAYqVcsSGskJFaGVUObbwyywGhVeDikLPCvkh8QwNTyF0OjfvtD/CPyYLi
    sOzmsr79zC8yWsTfiwe4d2uQ0RUTSdvYNwd9qcuYGX1rQX4q5PEDKsUNM/gJxnen
    ArOL+0umZ6XG3ScOP0ZRymnwLViMF7Tjhkw14qCHDllC3J+mMav+rwIMYjkesZMO
    AbL6xUe9AgMBAAECggEAXjsvglISnoI7E6BrXz2nWv7vDW56sYZFTQ90OKF8btKx
    vQi7blcd9MOUO0fDC+8R/mOzkdxL3R6w2fQpfDcVBCP7fk0Rx3C3FZb1EaAMSzcZ
    Hv8evfV8CCBVi72UqMAkQnTTaM+2EAZNuf+GVyEdUFmh/zoMoVkiJfiH0Z71UKW6
    9igkivgBB0Z6wUlOwP0mpogR+j5Y0e0Z/Eh/ScJfuJhmDNtlrFNcGDz1Y3ddtXjC
    nL/lHRTZU5EhuWZHXAs6jmv6YOnUlH9VYN6moKlBrtC2oeb1+FvKQC8yZdbrqMti
    7gj3bcAVFiiumGtp5DJrIP47hOGdw041EVvERTMA6QKBgQDkq67g19BO+lCDVnIm
    Fp+Qh34FxoA5pzv4pK1kz76G9duptCpvO7nQXERFGMjPZTJZR82+lq1YaM+30SfM
    LghOkW910Go77e8ts9SMInwjuTg1+8WGG20Ym/odg6/LU4f69WpY2K/7jE/GzZpW
    s+FH/uEaeqywD5EASlVcGerT/wKBgQDUnJLPNSYbcqMxbcVGhjOmcVAKSULWoffW
    B0OiJVT6DPIPNKXOA3n8JVnq7ubuNZMv9Arcwc/rZT48fT1SDNaplF3jK/BoqDGW
    kGkvtxbvrzGRDtS+kgmgyqIQ9kgJtEM9F3DiUnqwA9DAdOWPOFiNSZ9boitqAKBP
    gSzKgMA0QwKBgC7UDcsTxx/1WPmcgWHVbjXd2Wv7W5Ty73Aa4Tts47qlrKdTMwF2
    fLXzvzNbQPxf3/CyqKqoFrWtOSSOm5TPtHnKhMXeuXKuZjW4xwUvprZ2HtHHTosJ
    IM1SW+Uha6W65HT7Px0Uuu1LraarwjiRO8hPpO+UQbsIZQxnLJXg5NsnAoGAWoL9
    jPDXdD/tcZGFtmxTeLwskvR1W+JAHAGjrVevQXRZaFfFblrUh59vFDD4Ztiv/G4s
    Yaaw2UmUoTO/8zo7+J2NCrUd97ACzFJWNVYAkbFHrLVfpHGPX8BkFkyChn8TUOK1
    z+PFD0HQkN4zDDG0oRGCogP773isxqv7YYpGSPkCgYB89iD+Ay+C8OcnC+iOd0jl
    AUOEKksJroGx9p/ENjICQC7XuSQztYBGbLiJDTojHcXMICcY8xvucdGeZopUBa6o
    ncrlwnG4X3K4kHSoRqspvC6or2ZNChRKJr9gDlbwese7sEQH9eRfJS+gi6I49v+w
    ygLgR03UG5jC+9x6ucRhpw==
    -----END PRIVATE KEY-----

  jwt_public.pem: |
    -----BEGIN PUBLIC KEY-----
    MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAveoIk8PEPG+9aalcyIm6
    MPQxCH+plz1RaavmTfu5x3fXL74wZKm0C2lbxPSqhG7kcRhHVnSXKhNJnRDLrpIX
    zO5Amr9d7HbVJOgqxLJoSje9imLEYbdN/4/gWlayIJE1ofJ5UDbo/ongy6hFVLhh
    AGKlXLEhrJCRWhlVDm28MssBoVXg4pCzwr5IfEMDU8hdDo377Q/wj8mC4rDs5rK+
    /cwvMlrE34sHuHdrkNEVE0nb2DcHfanLmBl9a0F+KuTxAyrFDTP4CcZ3pwKzi/tL
    pmelxt0nDj9GUcpp8C1YjBe044ZMNeKghw5ZQtyfpjGr/q8CDGI5HrGTDgGy+sVH
    vQIDAQAB
    -----END PUBLIC KEY-----

---

apiVersion: v1
kind: Secret
metadata:
  name: review-secrets
  namespace: review
type: Opaque
stringData:
  jwt_public.pem: |
    -----BEGIN PUBLIC KEY-----
    MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAveoIk8PEPG+9aalcyIm6
    MPQxCH+plz1RaavmTfu5x3fXL74wZKm0C2lbxPSqhG7kcRhHVnSXKhNJnRDLrpIX
    zO5Amr9d7HbVJOgqxLJoSje9imLEYbdN/4/gWlayIJE1ofJ5UDbo/ongy6hFVLhh
    AGKlXLEhrJCRWhlVDm28MssBoVXg4pCzwr5IfEMDU8hdDo377Q/wj8mC4rDs5rK+
    /cwvMlrE34sHuHdrkNEVE0nb2DcHfanLmBl9a0F+KuTxAyrFDTP4CcZ3pwKzi/tL
    pmelxt0nDj9GUcpp8C1YjBe044ZMNeKghw5ZQtyfpjGr/q8CDGI5HrGTDgGy+sVH
    vQIDAQAB
    -----END PUBLIC KEY-----
---
apiVersion: v1
kind: Secret
metadata:
  name: report-secrets
  namespace: report
type: Opaque
stringData:
  jwt_public.pem: |
    -----BEGIN PUBLIC KEY-----
    MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAveoIk8PEPG+9aalcyIm6
    MPQxCH+plz1RaavmTfu5x3fXL74wZKm0C2lbxPSqhG7kcRhHVnSXKhNJnRDLrpIX
    zO5Amr9d7HbVJOgqxLJoSje9imLEYbdN/4/gWlayIJE1ofJ5UDbo/ongy6hFVLhh
    AGKlXLEhrJCRWhlVDm28MssBoVXg4pCzwr5IfEMDU8hdDo377Q/wj8mC4rDs5rK+
    /cwvMlrE34sHuHdrkNEVE0nb2DcHfanLmBl9a0F+KuTxAyrFDTP4CcZ3pwKzi/tL
    pmelxt0nDj9GUcpp8C1YjBe044ZMNeKghw5ZQtyfpjGr/q8CDGI5HrGTDgGy+sVH
    vQIDAQAB
    -----END PUBLIC KEY-----
  POSTGRES_URL: "postgresql+asyncpg://app:secret@postgresdb.report.svc.cluster.local:5432/reports"
  POSTGRES_PASSWORD: secret
  POSTGRES_USER: app
  POSTGRES_DB: reports  

---
apiVersion: v1
kind: Secret
metadata:
  name: rabbitmq-credentials
  namespace: review
type: Opaque
stringData:
  rabbitmq-password: "pass12345"
  rabbitmq-username: "admin"
---
apiVersion: v1
kind: Secret
metadata:
  name: rabbitmq-credentials
  namespace: submission
type: Opaque
stringData:
  rabbitmq-password: "pass12345"
  rabbitmq-username: "admin"
---
apiVersion: v1
kind: Secret
metadata:
  name: rabbitmq-credentials
  namespace: assignment
type: Opaque
stringData:
  rabbitmq-password: "pass12345"
  rabbitmq-username: "admin"
---
apiVersion: v1
kind: Secret
metadata:
  name: rabbitmq-credentials
  namespace: report
type: Opaque
stringData:
  rabbitmq-password: "pass12345"
  rabbitmq-username: "admin"
